build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"

sphinx:
  configuration: source/conf.py


python:
   install:
   - requirements: requirements.txt